# Generated by Django 3.1.1 on 2020-09-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0003_auto_20200910_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='fecha_creacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de creacion'),
        ),
        migrations.AddField(
            model_name='libro',
            name='fecha_creacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de creacion'),
        ),
    ]
